In [135]:
#1

import numpy as np

In [136]:
def f1(n):
    return np.array([i for i in range(n,-1, -1)])

In [137]:
r1 = f1(10)
r1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [138]:
#2

def f2(n):
    return np.diag([i for i in range(n,-1, -1)])

In [139]:
r2 = f2(10)
r2

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [140]:
r2.diagonal().sum()

55

In [141]:
#3

import pandas as pd

In [142]:
t3_data = pd.read_csv('C:/TestData/Movielens/ratings.csv')

In [143]:
movies = pd.read_csv('C:/TestData/Movielens/movies.csv')

In [144]:
t3_data = t3_data[t3_data['rating']>=5]

In [145]:
t3_res = t3_data.groupby(['movieId'])['rating'].agg(['sum']).reset_index()
movieId = t3_res[t3_res['sum']==t3_res['sum'].max()].reset_index().at[0,'movieId']

In [146]:
movies[movies['movieId']==movieId]

movieId                             title       genres
315      318  Shawshank Redemption, The (1994)  Crime|Drama

In [147]:
#4

In [157]:
t4_data = pd.read_csv('power.csv')

In [158]:
t4_data[t4_data['country'].str.contains('L') | t4_data['country'].str.contains('E') ]['country'].unique()

array(['Lithuania', 'Eritrea', 'Ethiopia', 'Lesotho', 'Latvia',
       'Luxembourg', 'United Arab Emirates', 'Ecuador', 'Egypt',
       'El Salvador', 'Estonia', 'Ethiopia, incl. Eritrea',
       "Lao People's Dem. Rep.", 'Liberia', 'Libya', 'Sri Lanka',
       'Sierra Leone', 'Equatorial Guinea', 'Lebanon', 'St. Lucia',
       'Bonaire, St Eustatius, Saba', 'Timor-Leste', 'Liechtenstein'],
      dtype=object)

In [159]:
t4_countries = t4_data[
    ((t4_data['country'] == 'Lithuania') | (t4_data['country'] == 'Latvia') | (t4_data['country'] == 'Estonia'))
    & 
    ((t4_data['category'] == 4) | (t4_data['category'] == 12) | (t4_data['category'] == 21))
    &
    (t4_data['year']>=2005)
    &
    (t4_data['year']<=2010)
    &
    (t4_data['quantity'] > 0)
]

In [160]:
t4_countries.tail()

country  year  quantity  category
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

In [161]:
t4_countries['quantity'].sum()

240580.0

In [162]:
#5

t5_a = np.array([[4,2,1],[1,3,0],[0,5,4]])
t5_b = np.array([4,12,-3])

In [163]:
from numpy import linalg

In [164]:
linalg.solve(t5_a, t5_b)

array([ 0.46666667,  3.84444444, -5.55555556])